PLUGIN = snipmate

SOURCE =    after/plugin/snipMate.vim  
SOURCE +=    autoload/snipMate.vim   
SOURCE +=    doc/snipMate.txt        
SOURCE +=    ftplugin/html_snip_helper.vim  
SOURCE +=    plugin/snipMate.vim     
SOURCE +=    snippets/_.snippets     
SOURCE +=    snippets/autoit.snippets  
SOURCE +=    snippets/c.snippets     
SOURCE +=    snippets/cpp.snippets   
SOURCE +=    snippets/html.snippets  
SOURCE +=    snippets/java.snippets  
SOURCE +=    snippets/javascript.snippets  
SOURCE +=    snippets/mako.snippets  
SOURCE +=    snippets/objc.snippets  
SOURCE +=    snippets/perl.snippets  
SOURCE +=    snippets/php.snippets   
SOURCE +=    snippets/python.snippets  
SOURCE +=    snippets/ruby.snippets  
SOURCE +=    snippets/sh.snippets    
SOURCE +=    snippets/snippet.snippets  
SOURCE +=    snippets/tcl.snippets   
SOURCE +=    snippets/tex.snippets   
SOURCE +=    snippets/vim.snippets   
SOURCE +=    snippets/zsh.snippets   
SOURCE +=    syntax/snippet.vim

include ../common/target.mk
