PLUGIN = omnicppcomplete

SOURCE = after/ftplugin/c.vim    
SOURCE += after/ftplugin/cpp.vim  
SOURCE += autoload/omni/common/debug.vim  
SOURCE += autoload/omni/common/utils.vim  
SOURCE += autoload/omni/cpp/complete.vim  
SOURCE += autoload/omni/cpp/includes.vim  
SOURCE += autoload/omni/cpp/items.vim  
SOURCE += autoload/omni/cpp/maycomplete.vim  
SOURCE += autoload/omni/cpp/namespaces.vim  
SOURCE += autoload/omni/cpp/settings.vim  
SOURCE += autoload/omni/cpp/tokenizer.vim  
SOURCE += autoload/omni/cpp/utils.vim  
SOURCE += doc/omnicppcomplete.txt 

include ../common/target.mk
